name = "AbstractWrappedDataFrames"
uuid = "fa347795-2256-4518-8e2a-87a426559093"
authors = ["Tom Kwong <tk3369@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"

[compat]
DataFrames = "0.21"
Lazy = "0.15"
julia = "1"

[extras]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CategoricalArrays", "PooledArrays", "Random", "Test"]
